apiVersion: v1
data:
  logstash.conf: "input {\n  beats {\n    port => \"5044\"\n  }\n}\n \noutput {\n
    \ elasticsearch {\n    hosts => [\"http://es-cluster:9200\"]\n    index => \"%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}\"\n
    \ }\n  stdout {\n    codec => rubydebug\n  }\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-10T19:40:55Z"
  name: logstash-pipeline
  namespace: logging
  resourceVersion: "2272779"
  uid: debf9c35-3ef0-4284-b37f-4d7e774c90b7
